name: Go Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  Test-Go:

    strategy:
      matrix:
        go: ["1.16","1.17","1.18", "1.19","1.20","1.21","1.22"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go - ${{matrix.go}}
      uses: actions/setup-go@v2
      with:
        go-version: ${{matrix.go}}

    - name: Test - ${{matrix.go}}
      run: go test ./template_test.go -v

