name: Go Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  Test-Go:

    strategy:
      matrix:
        go: ["1.11","1.12","1.13","1.14","1.15","1.16","1.17","1.18"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go - ${{matrix.go}}
      uses: actions/setup-go@v2
      with:
        go-version: ${{matrix.go}}

    - name: Test - ${{matrix.go}}
      run: go test ./template_test.go -v

